name: jaguar_json
description: jaguar_serializer based JSON interceptors for Jaguar
version: 0.1.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_json
documentation:

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: ^0.6.14
  jaguar_serializer: ^0.4.0

dev_dependencies:
  test: ^0.12.0
  jaguar_client: ^0.1.5
