name: jaguar_json
description: jaguar_serializer based JSON interceptors for Jaguar
version: 0.1.0
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_json

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  jaguar: '>=0.5.10 <0.6.0'
  jaguar_serializer: '>=0.3.9 <0.4.0'
  jaguar_reflect:
  teja_http_json: ^0.1.4

dev_dependencies:
  test: ^0.12.0
